---
version: 1.0

globel:

admin:
  params:
    orgName: Org3
    orgMSP: Org3MSP
    orgHost: org3.example.com
    orgAdmin: Admin
    configPath: ../../network/orgs/admin/admin-org3.yaml
  envs:
    - key: DISCOVERY_AS_LOCALHOST
      val: true
    - key: TEST_IN_SHELL
      val: false

app:
  params:
    orgName: Org3
    orgMSP: Org3MSP
    orgHost: org3.example.com
    orgAdmin: Admin
    configPath: ../../network/orgs/app/app-org3.yaml

    orgUser: User1
    credPath: ../../network/orgs/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp
    certPath: ../../network/orgs/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/signcerts/User1@org3.example.com-cert.pem
  envs:
    - key: DISCOVERY_AS_LOCALHOST
      val: true
    - key: TEST_IN_SHELL
      val: false
